### ISSUE TITLE
Under which licence is this library provided?

### ISSUE THREAD

**Issue by romaricpascal** [crubier/Hexastore#1]
I'd like to use that code in one of my projects, but I'm unsure if I can as there's no information about the licence. Could you clarify this, please?

**Comment by crubier** [comment]
Hello, this library is BSD licensed, I will add the license file in future commits:

BSD License

Copyright (c) 2014, Vincent Lecrubier. All rights reserved.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:
- Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.
- Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the
  documentation and/or other materials provided with the distribution.
- Neither the name Hexastore nor the names of its contributors may be used to
  endorse or promote products derived from this software without specific
  prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

**Comment by romaricpascal** [comment]
Brilliant! Thanks a lot :)

**Comment by crubier** [comment]
@rhumaric 

Please note that an improved, more flexible version of Hexastore has been released as Factis, and will see further development, while Hexastore is deprecated, being replaced by factis-store-hexastore :-) 

Check [factis.io](http://factis.io)
